// Copyright (c) 2020, VividSparks IT Solutions Pvt. Ltd.  All rights reserved.
//
// Redistribution and use in source and binary forms, modifications,
// are NOT permitted.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
// ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
// (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
// LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
// ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
// (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
// SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#ifndef RACER_MANYCORE_FEATURES_H
#define RACER_MANYCORE_FEATURES_H
// <features.h> sorts out many of these defines based on compile time flags (e.g. -std=c++11)
#include <features.h>
// check _RACER_SOURCE
#ifndef _BSD_SOURCE
#error "_BSD_SOURCE not defined: required for RacEr_manycore_runtime"
#endif

// check _XOPEN_SOURCE
#ifndef _XOPEN_SOURCE
#error "_XOPEN_SOURCE not defined: required for RacEr_manycore_runtime"
#else
#if _XOPEN_SOURCE < 500
#error "_XOPEN_SOURCE < 500: RacEr_manycore_runtime requires _XOPEN_SOURCE >= 500"
#endif
#endif

#endif
