#ifndef RACER_MANYCORE_MACHINE_H
#define RACER_MANYCORE_MACHINE_H
/* Chip address and data width */
#define RACER_MANYCORE_MACHINE_MAX_EPA_WIDTH 28
#define RACER_MANYCORE_MACHINE_DATA_WIDTH    32
/* Chip dimensions */
#define RACER_MANYCORE_PODS_Y         1
#define RACER_MANYCORE_PODS_X         1
/* Chip Pod dimensions */
#define RACER_MANYCORE_POD_TILES_Y         2
#define RACER_MANYCORE_POD_TILES_X         2
/* Host coordinates */
#define RACER_MANYCORE_MACHINE_HOST_COORD_X  \
    2
#define RACER_MANYCORE_MACHINE_HOST_COORD_Y  \
    0
/* NoC field widths */
#define RACER_MANYCORE_NOC_COORD_X_WIDTH 7
#define RACER_MANYCORE_NOC_COORD_Y_WIDTH 7
/* L2 cache parameters */
#define RACER_MANYCORE_MACHINE_VCACHE_WAYS   \
    4
#define RACER_MANYCORE_MACHINE_VCACHE_BANK_SETS   \
    64
#define RACER_MANYCORE_MACHINE_VCACHE_BLOCK_SIZE_WORDS \
    
#define RACER_MANYCORE_MACHINE_VCACHE_BANK_STRIPE_SIZE_WORDS \
    8
#define RACER_MANYCORE_MACHINE_VCACHE_BANKS \
    (2 * (RACER_MANYCORE_MACHINE_DIM_X))
#define RACER_MANYCORE_MACHINE_VCACHE_SETS \
    ((RACER_MANYCORE_MACHINE_VCACHE_BANK_SETS)*(RACER_MANYCORE_MACHINE_VCACHE_BANKS))
#endif
