
##########################################################
## User configuration
##########################################################

# Set up cad tools if using a non-RacEr_cadenv environment
export RACER_CADENV_DIR ?= $(HK_TOOLS_DIR)/RacEr_cadenv
-include $(RACER_CADENV_DIR)/cadenv.mk

# boards: ultra96v2, pynqz2, vu47p
# hosts : zynq, bridge
export BOARDNAME ?= pynqz2
#ifeq ($(BOARDNAME),ultra96v2)
#export PART ?= xczu3eg-sbva484-1-e
#export HOST ?= zynq
#else ifeq ($(BOARDNAME),pynqz2)
#export PART ?= xcu250-figd2104-2L-e
#export PART ?= xc7z100ffg900-2
export PART ?= xc7z020clg400-1
export HOST ?= zynq
#else ifeq ($(BOARDNAME),vu47p)
#export PART ?= xcvu47p-fsvh2892-3-e
#export HOST ?= bridge
#else
#$(error Invalid BOARDNAME)
#endif

